apiVersion: v1
kind: Service
metadata:
  name: {{ template "cp-zookeeper.fullname" . }}-headless
  labels:
    app.kubernetes.io/name: {{ template "cp-zookeeper.name" . }}
    helm.sh/chart: {{ template "cp-zookeeper.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - port: {{ .Values.serverPort }}
      name: server
    - port: {{ .Values.leaderElectionPort }}
      name: leader-election
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ template "cp-zookeeper.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}