apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "cp-zookeeper.fullname" . }}-pdb
  labels:
    app.kubernetes.io/name: {{ template "cp-zookeeper.name" . }}
    helm.sh/chart: {{ template "cp-zookeeper.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "cp-zookeeper.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  {{- if .Values.minAvailable }}
  minAvailable: {{ .Values.minAvailable }}
  {{- else }}
  maxUnavailable: 1
  {{- end }}
