{{- if .Values.consoleFrontend.ingress.enabled -}}
{{- $fullname := include "pnda.console-frontend.fullname" . -}}
{{- $servicePort := .Values.consoleFrontend.service.port -}}
{{- $ingressPath := .Values.consoleFrontend.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "pnda.console-frontend.labels" . | nindent 4 }}
{{- with .Values.consoleFrontend.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
    {{- range $host := .Values.consoleFrontend.ingress.hosts }}
    - host: {{ $host | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullname }}
              servicePort: {{ $servicePort }}
    {{- end }}
status:
  loadBalancer: {}
{{- end -}}
