#Headless service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pnda.package-repository.fullname" . }}
  labels:
    {{- include "pnda.package-repository.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.packageRepository.service.port }}
      targetPort: http
      protocol: TCP
      name: packagerepository
  selector:
    {{- include "pnda.package-repository.labels" . | nindent 4 }}

