{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cp-kafka.fullname" . }}-exporter-configmap
  labels:
    app.kubernetes.io/name: {{ template "cp-kafka.name" . }}
    helm.sh/chart: {{ template "cp-kafka.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  jmx-kafka-prometheus.yml: |+
{{ toYaml .Values.prometheus.config | indent 4 }}
{{- end }}