{{- if .Values.prometheus.enabled -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name}}-kafka-metrics
  labels:
    app.kubernetes.io/name: cp-kafka
    app.kubernetes.io/instance: {{ .Release.Name }}
spec: 
  selector: 
    app.kubernetes.io/name: {{ template "cp-kafka.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - port: {{ .Values.prometheus.port }}
    name: metrics
    targetPort: {{ .Values.prometheus.port }}
{{- end -}}