apiVersion: v1
kind: Service
metadata:
  name: {{ template "cp-kafka.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "cp-kafka.name" . }}
    helm.sh/chart: {{ template "cp-kafka.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - port: 9092
      name: broker
  selector:
    app.kubernetes.io/name: {{ template "cp-kafka.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}