apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cp-ksql-server.fullname" . }}-ksql-queries-configmap
  labels:
    app.kubernetes.io/name: {{ template "cp-ksql-server.name" . }}
    helm.sh/chart: {{ template "cp-ksql-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- $files := .Files }}
  {{- range tuple "queries.sql" }}
  {{ . }}: |-
{{ $files.Get . | indent 4 }}
  {{- end }}
