apiVersion: v1
kind: Service
metadata:
  name: {{ template "cp-ksql-server.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "cp-ksql-server.name" . }}
    helm.sh/chart: {{ template "cp-ksql-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
      - name: ksql-server
        port: {{ .Values.servicePort }}
  selector:
    app.kubernetes.io/name: {{ template "cp-ksql-server.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
