apiVersion: v1
kind: Service
metadata:
  name: {{ template "spark.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "spark.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ template "spark.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - port: {{ .Values.master.ui_port }}
      name: gui
    - port: {{ .Values.master.port }}
      name: spark
  selector:
    app.kubernetes.io/name: {{ template "spark.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}