#Headless service
apiVersion: v1
kind: Service
metadata:
  name: {{ template "spark.fullname" . }}-workers
  labels:
    app.kubernetes.io/name: {{ template "spark.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ template "spark.chart" . }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ template "spark.name" . }}-worker
    app.kubernetes.io/instance: {{ .Release.Name }}