## ----------------------------
## PNDA Components Configuration
## ----------------------------
prometheus:
  rbac:
    enabled: true
  serviceMonitor:
    hdfs:
      enabled: true
    kafka:
      enabled: true
    hbase:
      enabled: true
    spark:
      enabled: true
