apiVersion: v1
kind: Service
metadata:
  name: {{ template "cp-schema-registry.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "cp-schema-registry.name" . }}
    helm.sh/chart: {{ template "cp-schema-registry.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - name: schema-registry
      port: {{ .Values.servicePort }}
  selector:
    app.kubernetes.io/name: {{ template "cp-schema-registry.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
