{{- if .Values.testing.enabled -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "pnda.testing.fullname" . }}-tsdb
  labels:
    {{- include "pnda.testing.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.testing.schedule }}"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "pnda.testing.labels" . | nindent 12 }}
        spec:
          restartPolicy: Never
          containers:
            - name: {{ include "pnda.testing.name" . }}-tsdb
              image: "{{.Values.testing.image.repository }}:{{.Values.testing.image.tag }}"
              imagePullPolicy: {{ .Values.testing.image.pullPolicy }}
              command:
                - "python"
                - "monitor.py"
                - "--plugin"
                - "opentsdb"
                - "--display"
                - "--postjson"
                - "http://{{.Release.Name}}-console-backend-data-logger:3001/metrics"
                - "--extra"
                - "--hosts {{.Release.Name}}-opentsdb:4242"
              volumeMounts:
                - mountPath: /testing/logging.conf
                  subPath: logging.conf
                  name: logging-config
              resources:
{{ toYaml .Values.testing.resources | indent 16 }}
          volumes:
            - name: logging-config
              configMap:
                name: {{ include "pnda.testing.fullname" . }}
{{- end -}}