apiVersion: v1
kind: Service
metadata:
  name: {{ template "cp-kafka-rest.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "cp-kafka-rest.name" . }}
    helm.sh/chart: {{ template "cp-kafka-rest.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - name: rest-proxy
      port: {{ .Values.servicePort }}
  selector:
    app.kubernetes.io/name: {{ template "cp-kafka-rest.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
