{{- if and .Values.cluster.enabled (not .Values.sentinel.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "redis.fullname" . }}-slave
  labels:
    app.kubernetes.io/name: {{ template "redis.name" . }}
    helm.sh/chart: {{ template "redis.chart" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
{{- if .Values.slave.service.annotations }}
  annotations:
{{ toYaml .Values.slave.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.slave.service.type }}
  {{ if eq .Values.slave.service.type "LoadBalancer" -}} {{ if .Values.slave.service.loadBalancerIP -}}
  loadBalancerIP: {{ .Values.slave.service.loadBalancerIP }}
  {{ end -}}
  {{- end -}}
  ports:
  - name: redis
    port: {{ .Values.slave.service.port }}
    targetPort: redis
    {{- if .Values.slave.service.nodePort }}
    nodePort: {{ .Values.slave.service.nodePort }}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ template "redis.name" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    role: slave
{{- end }}
