apiVersion: v1
kind: Service
metadata:
  name: deployment-manager-git
  labels:
    {{- include "pnda.deployment-manager.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "pnda.deployment-manager.labels" . | nindent 4 }}
  ports:
    - port: 8099
      targetPort: git
      protocol: TCP
      name: git