apiVersion: v1
kind: Service
metadata:
  name: {{ include "pnda.deployment-manager.fullname" . }}
  labels:
    {{- include "pnda.deployment-manager.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "pnda.deployment-manager.labels" . | nindent 4 }}
  ports:
    - port: {{ .Values.deploymentManager.service.port }}
      targetPort: http
      protocol: TCP
      name: http
